name: AOS-ktlint
on:
  pull_request:
    branches:
      - AOS-develop
      - AOS-*/**
  push:
    paths:
      - '**.kt'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Create Properties File
      env:
        RELEASE_KEYSTORE: ${{ secrets.KEY_STORE_BASE_64 }}
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      run: |
          echo "$RELEASE_KEYSTORE" | base64 -d > AOS/app/release.keystore
          echo "$KEYSTORE_PROPERTIES" > AOS/keystore.properties
          echo "$LOCAL_PROPERTIES" > AOS/local.properties
    - name: Run ktlint
      run: cd AOS && chmod +x ./gradlew &&./gradlew ktlintCheck
