name: Cache server build and deploy

on:
  push:
    branches:
      - "BE-develop"
    paths:
      - "nestjs-BE/cache-server/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: BE-develop
          sparse-checkout: nestjs-BE
      - name: Login to github Packages
        run: echo ${{ secrets.PACKAGE_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.PACKAGE_USERNAME }} --password-stdin
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.PACKAGE_USERNAME }}/mindsync-cache-server ./nestjs-BE/cache-server
          docker push ghcr.io/${{ secrets.PACKAGE_USERNAME }}/mindsync-cache-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            eval "$(ssh-agent -s)"
            echo "${{ secrets.PRIVATE_SSH_KEY }}" | ssh-add -
            ssh -A ${{ secrets.PRIVATE_USER }}@${{ secrets.PRIVATE_HOST }} << ENDSSH
              echo "${{ secrets.PACKAGE_ACCESS_TOKEN }}" | docker login ghcr.io -u "${{ secrets.PACKAGE_USERNAME }}" --password-stdin
              docker pull ghcr.io/"${{ secrets.PACKAGE_USERNAME }}"/mindsync-cache-server
              docker stop mindsync_cache_server || true
              docker rm mindsync_cache_server || true
              docker run -d --name mindsync_cache_server -p "${{ secrets.SERVER_PORT }}":"${{ secrets.CONTAINER_PORT }}" -e MYSQL_DATABASE_URL="${{ secrets.MYSQL_DATABASE_URL }}" -e MONGODB_DATABASE_URL="${{ secrets.MONGODB_DATABASE_URL }}" ghcr.io/"${{ secrets.PACKAGE_USERNAME }}"/mindsync-cache-server
              docker image prune -af
            ENDSSH
